name: Data Generator Workflow

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs at midnight UTC every day
  workflow_dispatch:
jobs:
  run-data-generator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirments.txt

    - name: Run data generator script
      run: |
        python data_generator.py
